package main

// DO NOT EDIT, this file is generated by hover at compile-time for the mini_player plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	mini_player "github.com/tadjaur/mini_player/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&mini_player.MiniPlayerPlugin{}))
}
